name: Build & Release

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '8.17.0'
      - name: Build
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Copy&Paste detection
        run: npm run ci-cpd

  launch-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Check version
        run: echo "::set-output name=version::$(jq -r .version package.json)"
        id: version
      - name: Tag release
        uses: mathieudutour/github-tag-action@v5.5
        id: tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.version.outputs.version }}
      - name: Build changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.tag.outputs.new_tag }}
          name: "${{ github.event.repository.name }}-${{ steps.tag.outputs.new_tag }}"
          body: ${{ steps.changelog.outputs.changelog }}
