name: Build & Release

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '8.17.0'
      - name: Build
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Copy&Paste detection
        run: npm run ci-cpd

  launch-release:
    runs-on: ubuntu-latest
    steps:
      - name: version
        run: echo "::set-output name=version::$(jq -r .version ./package.json)"
	id: version
      - name: release 
        uses: "marvinpinto/action-automatic-releases@1.2.0"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.version.outputs.version }}
	  title: "${{github.repository}}-v${{ steps.version.outputs.version }}"
          prerelease: false
