name: Build & Release

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '8.17.0'
      - name: Build
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Copy&Paste detection
        run: npm run ci-cpd

  launch-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: ls
        run: ls -la
      - name: Check version
        run: echo "::set-output name=version::$(jq -r .version package.json)"
        id: version
      - name: Changelog
        uses: mikepenz/release-changelog-builder-action@v1.8.1
        id: changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: "ncipollo/release-action@v1"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "v${{ steps.version.outputs.version }}"
          name: "${{ github.repository.name }}-v${{ steps.version.outputs.version }}"
          body: ${{steps.github_release.outputs.changelog}}
